### PR TITLE
Automating binary attachments to release.

### PR DESCRIPTION
**Pull request by parro-it**
Hi, I'm trying to automate the process of binaries attachment to GH releases.
We previously discussed this stuff on #124.

I will use these binaries on [libui-download](https://github.com/parro-it/libui-download) to avoid compile libui on each libui-node install.

This is a work in progress. Just publish the PR to get early feedback from you...

Some open issues and questions:
- You can see the actual attached files [on this test release](https://github.com/parro-it/libui/releases/tag/test13). Please suggest improvement or changes to file names as you like.
- I created many tags on my fork to trigger travis release builds, I don't know if these could be polluting this PR. please double check!
- The travis yaml file is becoming a mess. I'm thinking of creating a scripts folder to move some commands there... thoughts?
- Actually, there is no binaries for windows and for linux 32bit. I could try [to use docker](https://github.com/travis-ci/travis-ci/issues/5770) on travis to get a 32bit env, and to use appveyor for windows build
- You'll have to change the secure key with one for your repo after merge the PR. The actual one it's for my fork...

### CODE REVIEW

File: .travis.yml [hunk 1]
```diff
@@ -1,24 +1,48 @@
...
-  - rm -rf *
-  - cmake .. -G "Unix Makefiles" -DBUILD_SHARED_LIBS=OFF
-  - make tester examples
+- if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update; fi
+- if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install libgtk-3-dev -y ||
+  sudo apt-cache search libgtk3; fi
+- if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; fi
+- if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew upgrade cmake; fi
+- mkdir build
+- mkdir artifacts
```
Comment (parro-it) [inline .travis.yml]: Here I made an artifacts dir to keep all zip files before deploying them

File: .travis.yml [hunk 2]
```diff
@@ -1,24 +1,48 @@
...
+- make tester examples
+- cd out
+- tar -cvf ../../artifacts/examples-static-$TRAVIS_OS_NAME-$TRAVIS_TAG.tar.gz controlgallery controlgallery histogram
+- tar -cvf ../../artifacts/libui-static-$TRAVIS_OS_NAME-$TRAVIS_TAG.tar.gz libui.a
+- cd ..
+- rm -rf *
+- cmake .. -G "Unix Makefiles"
+- make tester examples
+- if [ "$TRAVIS_OS_NAME" == "linux" ]; then rm out/libui.so; fi
+- if [ "$TRAVIS_OS_NAME" == "linux" ]; then mv out/libui.so.0 out/libui.so; fi
```
Comment (parro-it) [inline .travis.yml]: I remove the linked lib file and renamed the real one

File: .travis.yml [hunk 3]
```diff
@@ -1,24 +1,48 @@
...
+    secure: PXLSEazyWqtNMgdTRKAjeJwDHeXiIae0HguQNL6Imaub9ujcSNA7u2gOy0gF8OXoeD1yZNz6G6qodEQlW+d/+K+ZIdnXA6MiwJzYUO+yecfTElziOPtObf9taLvyuRVEpF5hAVfB6zLhhYVhjZ2UuhuREYaq30DyBpJRvpfyjnq3C17OYQk3S+SR3x8eTAqjc4H4R4jchyBdlC8g+rol4vvBFwie39lpqegqS24UKLVDzVK5ajxHCgSlxmoI6n6oWXgXGrT82NxtD6p93PsC6/HFEKDalZGAWddXE0QbA0czEyTdXJ4sHCWkT0zwjzneZneMVXNhwtyZ2BOUOZa9EP9PYv0/WwQtmp3ptR6ell3uAoGmxg/hpDGPTCZ+3EVvBHW1Xs+HZAx9VqtcXd08kO3i10/ioDDxvkFJnGZwFKX0d5U+Z/6hGICvoLKrZFSZlLmAecku4q9ju5Mtw1qREwrfV4N4o4/T35hoG4bShGXnlTHxbfsqTHx8A22mi5x0zPn0FBeQzWasGzXq0R3Pn5O/v+vzH2EKZFL9Gw++X/eDqchA0cSsA6gUnUanKUkVNCbSxzc8lh5bHNUkHSNAzFkqcN8CHO25H8sGpRm3wbGwSJEf2YnUfZlASevu4BNyKQOM/OTQeS1yYaQsNxXpXQ0u7KIQlq2Vs8646tDYSro=
+  skip_cleanup: true
+  file:
+    - ../artifacts/examples-static-$TRAVIS_OS_NAME-$TRAVIS_TAG.tar.gz
+    - ../artifacts/libui-static-$TRAVIS_OS_NAME-$TRAVIS_TAG.tar.gz
+    - ../artifacts/examples-shared-$TRAVIS_OS_NAME-$TRAVIS_TAG.tar.gz
+    - ../artifacts/libui-shared-$TRAVIS_OS_NAME-$TRAVIS_TAG.tar.gz
+  on:
+    repo: parro-it/libui
+    tags: true
```
Comment (parro-it) [inline .travis.yml]: This make the deploy process trigger only when you create a new tag on master branch

File: .travis.yml [hunk 4]
```diff
@@ -1,24 +1,48 @@
...
+- if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; fi
+- if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew upgrade cmake; fi
+- mkdir build
+- mkdir artifacts
+- cd build
+- cmake --version
+- cmake .. -G "Unix Makefiles" -DBUILD_SHARED_LIBS=OFF
+- make tester examples
+- cd out
+- tar -cvf ../../artifacts/examples-static-$TRAVIS_OS_NAME-$TRAVIS_TAG.tar.gz controlgallery controlgallery histogram
```
Comment (andlabs) [inline .travis.yml]: Typo

File: .travis.yml (hunk 2 above)
Comment (andlabs) [inline .travis.yml]: This is incorrect; the installed name of a so on linux will always have the version suffix, with the versionless name being just a symlink

File: .travis.yml [hunk 5]
```diff
@@ -1,24 +1,48 @@
...
+- rm -rf *
+- cmake .. -G "Unix Makefiles"
+- make tester examples
+- if [ "$TRAVIS_OS_NAME" == "linux" ]; then rm out/libui.so; fi
+- if [ "$TRAVIS_OS_NAME" == "linux" ]; then mv out/libui.so.0 out/libui.so; fi
+- if [ "$TRAVIS_OS_NAME" == "linux" ]; then LIB_FILE=libui.so; fi
+- if [ "$TRAVIS_OS_NAME" == "osx" ]; then LIB_FILE=libui.A.dylib; fi
+- cd out
+- tar -cvf ../../artifacts/examples-shared-$TRAVIS_OS_NAME-$TRAVIS_TAG.tar.gz controlgallery controlgallery histogram $LIB_FILE
+- tar -cvf ../../artifacts/libui-shared-$TRAVIS_OS_NAME-$TRAVIS_TAG.tar.gz $LIB_FILE
```
Comment (andlabs) [inline .travis.yml]: I'd actually rather have everything for an OS and build type in one archive, rather than a separate one for examples, especially since you're including the library in the examples archive anyway

File: .travis.yml [hunk 6]
```diff
@@ -1,24 +1,48 @@
...
+- cd ..
+
+deploy:
+  provider: releases
+  api_key:
+    secure: PXLSEazyWqtNMgdTRKAjeJwDHeXiIae0HguQNL6Imaub9ujcSNA7u2gOy0gF8OXoeD1yZNz6G6qodEQlW+d/+K+ZIdnXA6MiwJzYUO+yecfTElziOPtObf9taLvyuRVEpF5hAVfB6zLhhYVhjZ2UuhuREYaq30DyBpJRvpfyjnq3C17OYQk3S+SR3x8eTAqjc4H4R4jchyBdlC8g+rol4vvBFwie39lpqegqS24UKLVDzVK5ajxHCgSlxmoI6n6oWXgXGrT82NxtD6p93PsC6/HFEKDalZGAWddXE0QbA0czEyTdXJ4sHCWkT0zwjzneZneMVXNhwtyZ2BOUOZa9EP9PYv0/WwQtmp3ptR6ell3uAoGmxg/hpDGPTCZ+3EVvBHW1Xs+HZAx9VqtcXd08kO3i10/ioDDxvkFJnGZwFKX0d5U+Z/6hGICvoLKrZFSZlLmAecku4q9ju5Mtw1qREwrfV4N4o4/T35hoG4bShGXnlTHxbfsqTHx8A22mi5x0zPn0FBeQzWasGzXq0R3Pn5O/v+vzH2EKZFL9Gw++X/eDqchA0cSsA6gUnUanKUkVNCbSxzc8lh5bHNUkHSNAzFkqcN8CHO25H8sGpRm3wbGwSJEf2YnUfZlASevu4BNyKQOM/OTQeS1yYaQsNxXpXQ0u7KIQlq2Vs8646tDYSro=
```
Comment (andlabs) [inline .travis.yml]: What do these three lines above do?

**Comment by andlabs** [comment]
What is appveyor?

File: .travis.yml (hunk 2 above)
Comment (parro-it) [inline .travis.yml]: Right, I'll fix this

File: .travis.yml (hunk 5 above)
Comment (parro-it) [inline .travis.yml]: I made a separate archive only for lib because I don't want to increase file size I'll have to download, but I noticed they are really small ones, so ok. Maybe I put them in a `examples` folder?

File: .travis.yml (hunk 6 above)
Comment (parro-it) [inline .travis.yml]: `provider: releases` configure the travis deploy provider that attach the files to the GH tagged release, there are other that e.g. publish to npm or other package managers...

`api key` is an encrypted GH token that give travis access to your repo. This actually is the token for my fork repo, you'll have to generate one by yourself using `travis` command

**Comment by parro-it** [comment]
AppVeyor it's a CI environment similar to travis but running on windows. IT already support `cmake`, I think we could use it to add CI stuff for Windows environment too...

**Comment by andlabs** [comment]
Cool, that sounds great. I'll probably not do this right away, but rather closer to the Alpha 4 release, since I still have one more thing I promised I'd have in Alpha 4 to implement ([table views](https://i-msdn.sec.s-msft.com/dynimg/IC510722.png)).

**Comment by andlabs** [comment]
Also:

The thing with a separate examples directory is that the executables are programmed to look for the libui shared object first in the *same directory as the executable*, and then in system directories.

On second thought, if it makes distribution easier for other languages, then a library-only archive would work.

**Comment by parro-it** [comment]
I'll continue to improve the PR, in the meanwhile I'll use my fork releases as a test repo for my `libui-download` module. What do you think about the creation of a `scripts` folder to write some shell scripts there and simplify the config file?

**Comment by andlabs** [comment]
What did you have in mind?

**Comment by parro-it** [comment]
e.g. to create a script `scripts/install-gtk`:

```bash
if [ "$TRAVIS_OS_NAME" == "linux" ]; then 
   sudo apt-get update; fi
  sudo apt-get install libgtk-3-dev -y ||  sudo apt-cache search libgtk3; 
fi

if [ "$TRAVIS_OS_NAME" == "osx" ]; then 
    brew update; 
    brew upgrade cmake; 
fi
```

and then call it from the config instead of executing all the instructions directly...

**Comment by parro-it** [comment]
This should make the travis config cleaner...

**Comment by andlabs** [comment]
That'll be fin, yes.

Will the Windows stuff build as both MSVC and MinGW?

**Comment by parro-it** [comment]
> That'll be fine, yes.

Right, I'll produce both batch for win and bash scripts for linux & osx.

> Will the Windows stuff build as both MSVC and MinGW?

RIght now I'm working with MSVC, but appveyor also includes MinGW environment, so it will be next step

**Comment by parro-it** [comment]
I have some problem building RELEASE, with `MSBuild C:\projects\libui\build\ALL_BUILD.vcxproj /p:Configuration=Debug` command. I get:

```
Build FAILED.
 
"C:\projects\libui\build\ALL_BUILD.vcxproj" (default target) (1) ->
"C:\projects\libui\build\libui.vcxproj" (default target) (3) ->
(ClCompile target) -> 
  cl : Command line error D8016: '/O2' and '/RTCu' command-line options are incompatible [C:\projects\libui\build\libui.vcxproj]
 
    0 Warning(s)
    1 Error(s)
```

Any hint about? The build is successfully using DEBUG configuration...

**Comment by andlabs** [comment]
I manually specified [`/RTCu`](https://msdn.microsoft.com/en-us/library/8wtf2dfz.aspx); I forget why (probably to be safest). You can try removing that from your CMakeLists.txt and trying again. If after doing that there are others that conflict with `/O2` please let me know so I can figure out what to do with them.

**Comment by parro-it** [comment]
I have to remove /RTC1 /RTCs flags too. They give the same conflict as /RTCu.
Without all that flags the release build pass.

**Comment by andlabs** [comment]
All right. I could make those three debug-only somehow. I would just need to dive back in and see how it's done :D

**Comment by parro-it** [comment]
Ok, the project build on AppVeyor with release config, you can  check the last build output [here](https://ci.appveyor.com/project/parro-it/libui/build/1.0.24).

I proceed creating artifacts deploy configuration.

**Comment by parro-it** [comment]
Some quick update on this stuff:

* [x] windows 64
* [ ] windows 32
* [x] OSX 64
* [ ] linux 32 - done, but binaries are not working
* [x] linux 64
* [x] bash scripts folder
* [ ] win batch scripts folder

File: CMakeLists.txt [hunk 7]
```diff
@@ -67,9 +67,9 @@ endif()
 
 if(BUILD_32)
 
-  CMAKE_GENERATOR_PLATFORM=ia32
+  set(CMAKE_GENERATOR_PLATFORM ia32)
 else()
-  CMAKE_GENERATOR_PLATFORM=x64
+  set(CMAKE_GENERATOR_PLATFORM x64)
 endif()
```
Comment (andlabs) [inline CMakeLists.txt]: libui should be able to be built for non-x86 platforms as well.

Comment (parro-it) [inline CMakeLists.txt]: You're right... I can specify the CMAKE_GENERATOR_PLATFORM as a cmd line argument, and remove BUILD_32 argument.

**Comment by andlabs** [comment]
Note the following:

```
commit a9c7ff9c6c98a560b498fdc36095954a8cb6a9ae
Author: Pietro Gagliardi <pietro10@mac.com>
Date:   Mon Oct 17 14:25:32 2016 -0400

    Travis now installs the right version of cmake by default on OS X. No more special hacks.

diff --git a/.travis.yml b/.travis.yml
index edd561b..d271bd8 100644
--- a/.travis.yml
+++ b/.travis.yml
@@ -13,7 +13,6 @@ script:
   - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update; fi
   - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install libgtk-3-dev -y || sudo apt-cache search libgtk3; fi
   - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; fi
-  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew upgrade cmake; fi 
   - mkdir build
   - cd build
   - cmake --version
```

This *should* fix OS X Travis builds failing now.

**Comment by andlabs** [comment]
Why close this?

**Comment by parro-it** [comment]
I'm doing some clean up of my older PRs. I can re-open it if there's interested

**Comment by ebraminio** [comment]
Yes, please re-open this fantastic work. Thanks

**Comment by parro-it** [comment]
> Yes, please re-open this fantastic work. Thanks

:heart: I'm glad of your appreciation! reopened

**Comment by ebraminio** [comment]
Definitely, @andlabs will hopefully soon merge utflib-and-attrstr branch, after that I guess he will be more active on merging community changes.

**Comment by andlabs** [comment]
Yes, I'm back at (mostly) full speed again.

**Comment by parro-it** [comment]
😎

**Comment by parro-it** [comment]
Nice to see you back @andlabs. I see you published a new relase some days ago, so I'm thinking to update this PR to support it. Or do you feel it's better to wait some time? Any thought? Comments?

**Comment by parro-it** [comment]
Oh, by the way, did you notice that libui is trendy on Github during the last three days?

**Comment by andlabs** [comment]
Hi. No I didn't notice that; did something happen? I'll check that out in a bit...

I actually want to start moving toward using this for building the binary packages, but now that the linux 386 static builds have stopped working I'll have to investigate build system issues before we can flip that switch. How much work does this PR accomplish so far?

**Comment by parro-it** [comment]
> Hi! No I didn't notice that; did something happen? I'll check that out in a bit...
Oh, well, not directly it, but https://github.com/kusti8/proton-native
is based on it. It is react-native for desktop (I still have to try it, but it is gaining lot of stars so it should be good :-) )

>  How much work does this PR accomplish so far?

I honestly don't remember at the moment :-) . I give it a look at it in next days and I'll says you...

**Comment by parro-it** [comment]
I just merged changes upstream. [Windows build](https://ci.appveyor.com/project/parro-it/libui/build/1.0.161) and [macOS build](https://travis-ci.org/parro-it/libui/jobs/343559432)  are successfull compiled, but [linux build](https://travis-ci.org/parro-it/libui/jobs/343559429) is failing, I need to investigate further...

**Comment by parro-it** [comment]
It' finally working! It appear that the docker image for 32bit Ubuntu is not supporting version 14.04 anymore. Now it compile on version 16.04.

**Comment by parro-it** [comment]
🎉 I just published release alpha-3.5 on my fork, it's here: https://github.com/parro-it/libui/releases/tag/alpha3.5-004

**Comment by mischnic** [comment]
The build failed because of https://github.com/andlabs/libui/issues/302#issuecomment-374043586 but travis is reporting "successful".

**Comment by mischnic** [comment]
Somehow, this is really getting messy.
Are there other fixes in here other than CI?
https://github.com/andlabs/libui/pull/157/commits/0cd14fd4b70bacfea91b657f01d229262094ee6d really shouldn't be necessary, because of https://github.com/andlabs/libui/commit/242620ff0f111898e61f84b1dc758cc0be67c28d

> Also the only C++ on OS X right now is the cpp-multithread example

**Comment by parro-it** [comment]
> Are there other fixes in here other than CI?

No, the only purpose of this PR is to publish prebuilt binaries on github for each new tagged release

> 0cd14fd really shouldn't be necessary, because of 242620f

You're right, I'll try to revert that.

**Comment by parro-it** [comment]
I'm trying to publish a new release out of current status of master:

macOS and Linux compile, but with some warnings:
https://travis-ci.org/parro-it/libui/builds/368775357

Windows instead give errors, they seems to be related to the new timer functionality:
```
(ClCompile target) -> 
  C:\projects\libui\windows\main.cpp(137): error C2440: '=' : cannot convert from 'int (__cdecl *)(void *)' to 'void (__cdecl *)(void *)' [C:\projects\libui\build\libui.vcxproj]
  C:\projects\libui\windows\utilwin.cpp(42): error C2171: '!' : illegal on operands of type 'void' [C:\projects\libui\build\libui.vcxproj]
  C:\projects\libui\windows\utilwin.cpp(42): error C2451: conditional expression of type 'void' is illegal [C:\projects\libui\build\libui.vcxproj]
    205 Warning(s)
    3 Error(s)
Time Elapsed 00:00:45.04

```

The full build log is here on AppVeyor:
https://ci.appveyor.com/project/parro-it/libui

/CC @andlabs @cody271

**Comment by parro-it** [comment]
On Windows, f is declared as a void returning function:

https://github.com/andlabs/libui/blob/591b9c87721b2e38fe6b2b1c455187375c764fa6/windows/uipriv_windows.hpp#L98-L102

But here it's result is negated as it's returning an int:

https://github.com/andlabs/libui/blob/591b9c87721b2e38fe6b2b1c455187375c764fa6/windows/utilwin.cpp#L40-L46

And here, it's set an int returning function:

https://github.com/andlabs/libui/blob/591b9c87721b2e38fe6b2b1c455187375c764fa6/windows/main.cpp#L132-L142

**Comment by mischnic** [comment]
Should most definitely be (as in unix/main.c):

```c
struct timer {
  int (*f)(void *);
  void *data;
};
```

@andlabs Why isn't this using `uiForEach` ?

**Comment by cody271** [comment]
@andlabs changed it from a class to a struct [here](https://github.com/andlabs/libui/commit/cac4cd9e81c13017d14343f0920b102451855110#diff-3255e95213da0f72b5a696fee83a5529). @mischnic is correct, `void` should be `int`. 
(Not sure what `uiForEach` would do for us here though..)

@parro-it We desperately need AppVeyor CI on the main build to catch these sorts of problems!
Can you maybe break out your `appveyor.yml` without build artifacts into a separate PR? Thanks.

**Comment by parro-it** [comment]
Trying that fix: https://ci.appveyor.com/project/parro-it/libui/build/1.0.180

**Comment by parro-it** [comment]
It compile indeed!

> @parro-it We desperately need AppVeyor CI on the main build to catch these sorts of problems!
Can you maybe break out your appveyor.yml without build artifacts into a separate PR? Thanks.

As it works now, artifacts are only published when new tags are pushed, not for normal commits. Anyway, I'm fine about splitting this PR if that could help.

**Comment by parro-it** [comment]
I created a PR for the fix https://github.com/andlabs/libui/pull/340

**Comment by andlabs** [comment]
Oops. Can't fix it until I leave work though.

**Comment by andlabs** [comment]
And yes, as for `uiForEach` I would need to make its name a bit more generic. `Continue` and `Stop` make as much sense for this. One of the TODOs I added to ui.h talks about this.

**Comment by parro-it** [comment]
> Oops. Can't fix it until I leave work though.

Take your time, I stop working on this now anyway, tomorrow I'll get married, I should prepare 🎉🎉🎉

**Comment by andlabs** [comment]
Congratulations!

**Comment by mischnic** [comment]
Congratulations!

**Comment by cody271** [comment]
@parro-it Congratulazioni amico mio!

**Comment by parro-it** [comment]
😢 Grazie mille! 
Ehi ma parliamo tutti italiano qui? 🤪

**Comment by mischnic** [comment]
Ma certo!

**Comment by cody271** [comment]
Spagnolo e un po 'di portoghese. Sono simili. ;-)

**Comment by parro-it** [comment]
> Spagnolo e un po 'di portoghese. Sono simili. ;-)

yo también un poco 😀

**Comment by andlabs** [comment]
Is this PR still relevant? I thought I merged it already...

**Comment by parro-it** [comment]
Oh, I thought you already closed it.
I think it's now completely covered by all the good work on the Travis builds.
I close it.

**Comment by parro-it** [comment]
Happy new year!!🎉🎉
