### ISSUE TITLE
Doesn't compile with Clang 7.0.0

### ISSUE THREAD

**Issue by khang06** [andlabs/libui#439]
Hey, I'm trying to compile libui on Clang 7.0.0 on MSYS2 MinGW 64-bit. However, I get this error.
```
H:/Github/libui/windows/areadraw.cpp:81:7: error: case value evaluates to 2291728396, which cannot be narrowed to type 'HRESULT' (aka 'long') [-Wc++11-narrowing]
        case D2DERR_RECREATE_TARGET:
             ^
C:\msys64\mingw64\x86_64-w64-mingw32\include\d2derr.h:30:33: note: expanded from macro 'D2DERR_RECREATE_TARGET'
#define D2DERR_RECREATE_TARGET   0x8899000C
```
It compiles fine with GCC 8.2.0.

**Comment by mischnic** [comment]
p7zip has done this: (https://svnweb.freebsd.org/ports/head/archivers/p7zip/files/patch-CPP_Windows_ErrorMsg.cpp?view=markup&pathrev=458172)
```c
	case (DWORD)(D2DERR_RECREATE_TARGET):
```

(Windows is a mess 🙈)
